# Generated by Django 5.2.5 on 2025-08-15 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('raion', models.CharField(blank=True, max_length=255, null=True)),
                ('amplasare', models.TextField(blank=True, null=True)),
                ('proprietar', models.CharField(blank=True, max_length=255, null=True)),
                ('suprafata_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('category', models.CharField(blank=True, max_length=120, null=True)),
                ('subcategory', models.CharField(blank=True, max_length=120, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['raion'], name='core_reserv_raion_87b6ce_idx')],
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denumire_stiintifica', models.CharField(max_length=255, unique=True)),
                ('denumire_populara', models.CharField(blank=True, max_length=255, null=True)),
                ('clasa', models.CharField(blank=True, max_length=120, null=True)),
                ('familia', models.CharField(blank=True, max_length=120, null=True)),
                ('habitat', models.CharField(blank=True, max_length=120, null=True)),
                ('localitatea', models.CharField(blank=True, max_length=255, null=True)),
                ('silvice', models.BooleanField(default=False)),
                ('pajisti_sau_stepice', models.BooleanField(default=False)),
                ('stancarii', models.BooleanField(default=False)),
                ('palustre_si_acvatice', models.BooleanField(default=False)),
                ('p_rara', models.BooleanField(default=False)),
                ('conventia_berna', models.BooleanField(default=False)),
                ('directiva_habitate', models.BooleanField(default=False)),
                ('cartea_rosie', models.PositiveSmallIntegerField(blank=True, help_text='Anul ediției Cărții Roșii în care planta este inclusă (ex: 2015)', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['familia'], name='core_specie_familia_fe3d57_idx'), models.Index(fields=['p_rara'], name='core_specie_p_rara_d94577_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReserveAssociationYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserve_links', to='core.association')),
                ('reserve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='association_links', to='core.reserve')),
            ],
            options={
                'indexes': [models.Index(fields=['reserve'], name='core_reserv_reserve_b69616_idx'), models.Index(fields=['association'], name='core_reserv_associa_f01129_idx'), models.Index(fields=['year'], name='core_reserv_year_dbe232_idx')],
                'unique_together': {('association', 'reserve', 'year')},
            },
        ),
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('rarity_at_observation', models.CharField(max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('observer', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reserve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='core.reserve')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='core.species')),
            ],
            options={
                'indexes': [models.Index(fields=['reserve', 'year'], name='core_occurr_reserve_de01d1_idx'), models.Index(fields=['species'], name='core_occurr_species_08f08a_idx'), models.Index(fields=['year'], name='core_occurr_year_a01d57_idx')],
                'unique_together': {('species', 'reserve', 'year')},
            },
        ),
    ]
