# Generated by Django 5.2.5 on 2025-08-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='species',
            name='cartea_rosie_cat',
            field=models.CharField(blank=True, help_text='Categoria din Cartea Roșie (ex.: VU, EN, CR)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='frecventa',
            field=models.CharField(blank=True, help_text='Frecvența (ex.: C, Rară, etc.)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='cartea_rosie',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Anul ediției Cărții Roșii (ex.: 2015)', null=True),
        ),
        migrations.AddIndex(
            model_name='species',
            index=models.Index(fields=['cartea_rosie_cat'], name='core_specie_cartea__435194_idx'),
        ),
        migrations.AddIndex(
            model_name='species',
            index=models.Index(fields=['frecventa'], name='core_specie_frecven_b1b444_idx'),
        ),
    ]
