# Generated by Django 5.2.5 on 2025-08-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_species_cartea_rosie_cat_species_frecventa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='p_rara',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
