# Generated by Django 5.2.5 on 2025-08-15 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_species_p_rara'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='coords_raw',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserve',
            name='diversitatea_fitocenotica',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserve',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='reserve',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
