# Generated by Django 5.2.5 on 2025-08-16 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_reserve_coords_raw_reserve_diversitatea_fitocenotica_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occurrence',
            name='rarity_at_observation',
        ),
        migrations.AddField(
            model_name='occurrence',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='rarity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='occurrence',
            index=models.Index(fields=['rarity'], name='core_occurr_rarity_f231d3_idx'),
        ),
    ]
