# Generated by Django 5.2.5 on 2025-08-17 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_species_p_rara'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='species',
            name='core_specie_p_rara_d94577_idx',
        ),
        migrations.RemoveField(
            model_name='species',
            name='p_rara',
        ),
    ]
