# Generated by Django 5.2.5 on 2025-08-18 13:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_is_rare_species'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='occurrence',
            name='core_occurr_rarity_f231d3_idx',
        ),
        migrations.RenameField(
            model_name='occurrence',
            old_name='rarity',
            new_name='is_rare',
        ),
        migrations.AlterField(
            model_name='species',
            name='is_rare',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='occurrence',
            index=models.Index(fields=['is_rare'], name='core_occurr_is_rare_c1462b_idx'),
        ),
        migrations.AddIndex(
            model_name='species',
            index=models.Index(fields=['is_rare'], name='core_specie_is_rare_5d6106_idx'),
        ),
    ]
