# Generated by Django 5.2.5 on 2025-08-29 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_occurrence_core_occurr_rarity_f231d3_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_english', models.CharField(db_index=True, max_length=255, unique=True)),
                ('name_romanian', models.CharField(db_index=True, max_length=255, unique=True)),
                ('code', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_habitat',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True, verbose_name='codul_sitului')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='denumirea')),
                ('surface_ha', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='suprafata (ha)')),
                ('bird_species_count', models.IntegerField(verbose_name='numar_specii_pasari')),
                ('other_species_count', models.IntegerField(verbose_name='alte_specii')),
                ('habitats_count', models.IntegerField(verbose_name='habitate')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('ste', models.BooleanField(verbose_name='STE')),
                ('conj', models.BooleanField(verbose_name='CONJ')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_site',
                'indexes': [models.Index(fields=['name'], name='core_site_name_97584f_idx'), models.Index(fields=['code'], name='core_site_code_b3ebd9_idx')],
            },
        ),
        migrations.CreateModel(
            name='SiteHabitat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.SmallIntegerField(blank=True, db_index=True, null=True)),
                ('surface', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('habitat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitat_sites', to='core.habitat')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_habitats', to='core.site')),
            ],
            options={
                'db_table': 'core_site_habitat',
                'unique_together': {('site', 'habitat', 'year')},
            },
        ),
    ]
