# Generated by Django 5.2.5 on 2025-08-29 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_habitat_site_sitehabitat'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sitehabitat',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='sitehabitat',
            name='habitat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_habitats', to='core.habitat'),
        ),
        migrations.AlterField(
            model_name='sitehabitat',
            name='year',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AddIndex(
            model_name='sitehabitat',
            index=models.Index(fields=['year'], name='core_siteha_year_0f59e9_idx'),
        ),
        migrations.AddIndex(
            model_name='sitehabitat',
            index=models.Index(fields=['site', 'year'], name='core_siteha_site_id_1e6ff0_idx'),
        ),
        migrations.AddIndex(
            model_name='sitehabitat',
            index=models.Index(fields=['habitat', 'year'], name='core_siteha_habitat_4c4ebb_idx'),
        ),
        migrations.AddConstraint(
            model_name='sitehabitat',
            constraint=models.UniqueConstraint(fields=('site', 'habitat', 'year'), name='uniq_site_habitat_year'),
        ),
        migrations.AlterModelTable(
            name='sitehabitat',
            table=None,
        ),
    ]
