# Generated by Django 5.2.5 on 2025-09-01 09:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_sitehabitat_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='habitats_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='habitate'),
        ),
        migrations.AlterField(
            model_name='sitehabitat',
            name='surface',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
