# Generated by Django 5.2.5 on 2025-09-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_site_habitats_count_alter_sitehabitat_surface'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
