# Generated by Django 5.2.5 on 2025-09-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_swap_site_lat_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='bio_region_continentala',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='site',
            name='bio_region_stepica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='site',
            name='other_species',
            field=models.TextField(blank=True, default=''),
        ),
    ]
