# Generated by Django 5.2.5 on 2025-09-08 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_drop_site_bio_region_flags'),
        ('core', '0017_site_bio_region_continentala_site_bio_region_stepica_and_more'),
    ]

    operations = [
    ]
